=== Richard-Linsdale/nbpcg/src/main/resources/uk/org/rlinsdale/nbpcg/nbpcg.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    SYSTEM ID  : nbres:/uk/org/rlinsdale/nbpcg/nbpcg.dtd

    Author     : Richard Linsdale (richard.linsdale at blueyonder.co.uk)
-->

<!ELEMENT nbpcg (build, node+, databases+) >
    <!ATTLIST nbpcg
        name CDATA #REQUIRED
        >
    <!ELEMENT build (project+) >
        <!ATTLIST build
            viewerroles CDATA #REQUIRED
            copyright CDATA #REQUIRED
            >
        <!ELEMENT project (generate*) >
            <!ATTLIST project
                name CDATA #REQUIRED
                log CDATA #REQUIRED
                license (gpl30|lgpl21) #IMPLIED
                >
            <!ELEMENT generate EMPTY>
                <!ATTLIST generate
                    type (data|node|nodeviewer|nodeeditor|remotedb|mysqldatabase|jsondatabase) #REQUIRED
                    package CDATA #REQUIRED
                    >
    <!ELEMENT node (node*)>
        <!ATTLIST node
            name CDATA #REQUIRED
            view (both|icon|tree|none) #IMPLIED
            viewers CDATA #IMPLIED
            dbname CDATA #IMPLIED
            rootlabel CDATA #IMPLIED
            rooticon CDATA #IMPLIED
            icon CDATA #IMPLIED
            label CDATA #IMPLIED
            orderable (yes) #IMPLIED
            nullallowed (yes) #IMPLIED
            fkey (no) #IMPLIED
            displaynameformat CDATA #IMPLIED
            displaytitleformat CDATA #IMPLIED
            sortformat CDATA #IMPLIED
            min CDATA #IMPLIED
            max CDATA #IMPLIED
            >
    <!ELEMENT databases (database+)>
        <!ELEMENT database (table+)>
            <!ATTLIST database
                name CDATA #REQUIRED
                dbname CDATA #IMPLIED
                db (MySQL|Remote-MySQL) #IMPLIED
                type (idkeyauto) #IMPLIED
                withfields (idandstamp) #IMPLIED
                usepackage CDATA #IMPLIED
                >
            <!ELEMENT table (field*,insertrecord*)>
                <!ATTLIST table
                    name CDATA #REQUIRED
                    dbname CDATA #IMPLIED
                    type (idkeyauto) #IMPLIED
                    withfields (idandstamp) #IMPLIED>
                <!ELEMENT field EMPTY>
                    <!ATTLIST field
                        name CDATA #REQUIRED
                        dbname  CDATA #IMPLIED
                        index (unique|yes) #IMPLIED
                        unique (yes) #IMPLIED
                        type (boolean|long|int|date|datetime|enum|reference|password) #IMPLIED
                        nullallowed (yes) #IMPLIED
                        label CDATA #IMPLIED
                        references CDATA #IMPLIED
                        fkey (no) #IMPLIED
                        values CDATA #IMPLIED
                        min CDATA #IMPLIED
                        max CDATA #IMPLIED
                        future (yes) #IMPLIED
                        past (yes) #IMPLIED
                        passwordsupport CDATA #IMPLIED
                        entryfield CDATA #IMPLIED
                        passwordstrength (weak|strong|verystrong) #IMPLIED
                        >
                <!ELEMENT insertrecord (insertfield*)>
                    <!ELEMENT insertfield EMPTY>
                        <!ATTLIST insertfield
                            name CDATA #REQUIRED
                            value CDATA #REQUIRED
                        >

=== Richard-Linsdale/nbpcg/src/main/resources/uk/theretiredprogrammer/nbpcg/NBPCG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nbpcg PUBLIC "-//uk/theretiredprogrammer/nbpcg/DTD NBPCG SCHEMA 1.0//EN"
"nbres:/uk/theretiredprogrammer/nbpcg/nbpcg.dtd" >

<nbpcg name="?">
    
    <build viewerroles="?">
        <project name="?" log="?.?.?">
            <generatescripts/>
            <generate type="?" package="p.p.p" />
        </project>
    </build>
    
    <node name="x">
        
    </node>
    
    <databases>
        <database name="?">
            <table name="?">
                <field name="?"/>
                <insert values="?" />
            </table>
        </database>
    </databases>
</nbpcg>

=== Richard-Linsdale/nbpcg/src/main/resources/uk/org/rlinsdale/nbpcg/NBPCG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nbpcg PUBLIC "-//uk/org/rlinsdale/nbpcg/DTD NBPCG SCHEMA 1.0//EN"
    "nbres:/uk/org/rlinsdale/nbpcg/nbpcg.dtd" >

<nbpcg name="a" >
    
    <build >
        <project name="p" log="l">
            <generate type="z" package="p.p.p" />
        </project>
    </build>
    
    <node name="x" icon="y" rooticon="z" >
        
    </node>
    
    <databases>
        <database name="x" >
            <table name="x">
                <field name="x"/>
                <insert values="z" />
            </table>
        </standard>
    </databases>
</nbpcg>
