=== Richard-Linsdale/nbpcg/src/main/resources/uk/org/rlinsdale/nbpcg/nbpcgbuild.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    SYSTEM ID  : nbres:/uk/org/rlinsdale/nbpcg/nbpcgbuild.dtd

    Author     : Richard Linsdale (richard.linsdale at blueyonder.co.uk)
-->

<!ELEMENT nbpcg-build (folder+, execute+) >
    <!ATTLIST nbpcg-build
        name CDATA #REQUIRED
        >
    <!ELEMENT folder EMPTY >
        <!ATTLIST folder
            location (java|resource|project) #REQUIRED
            name CDATA #REQUIRED
            project CDATA #REQUIRED
            package CDATA #IMPLIED
            >
    <!ELEMENT execute EMPTY >
        <!ATTLIST execute
            action (message|entitytemplate) #REQUIRED
            message CDATA #IMPLIED
            template CDATA #IMPLIED
            type CDATA #IMPLIED
            folder CDATA #IMPLIED
            filename CDATA #IMPLIED
            usedbinfo CDATA #IMPLIED
            useentityinfo CDATA #IMPLIED
            usefield CDATA #IMPLIED
            log CDATA #IMPLIED
            package CDATA #IMPLIED
            datapackage CDATA #IMPLIED
            nodepackage CDATA #IMPLIED
            nodeeditorpackage CDATA #IMPLIED
            license CDATA #IMPLIED
            copyright CDATA #IMPLIED
            >

=== Richard-Linsdale/nbpcg/src/main/generated-xml/cdarchive-build.xml
<?xml version="1.0" encoding="UTF-8"?>
    
    <!DOCTYPE nbpcg-build PUBLIC "-//uk/org/rlinsdale/nbpcgbuild/DTD NBPCGBUILD SCHEMA 1.0//EN" "nbres:/uk/org/rlinsdale/nbpcg/nbpcgbuild.dtd">
<nbpcg-build name="CD Archive" copyright="2014-2015 Richard Linsdale (richard.linsdale at blueyonder.co.uk)">
    <folder project="CD Archive - generated" location="resource" package="uk.org.rlinsdale.cdarchive.mysql" message="generating mysql script files for cdarchive" log="linsdale.cdarchive" license="gpl30">
        <execute template="createsqldatabase" filename="createdb.sql" usepersistencestore="cdarchive"/>
        <execute template="backupscript" filename="backupscript.sh" usepersistencestore="cdarchive"/>
        <execute template="createsqltables" filename="createtables.sql" usepersistencestore="cdarchive"/>
    </folder>
    <folder project="CD Archive - generated" location="java" package="uk.org.rlinsdale.cdarchive.dataobjects" message="generating entity files" log="linsdale.cdarchive" license="gpl30">
        <execute template="rootentity" filename="CdRoot.java" useentityinfo="CdRoot"/>
        <execute template="rootentity" filename="FileRoot.java" useentityinfo="FileRoot"/>
        <execute template="rootentity" filename="FolderRoot.java" useentityinfo="FolderRoot"/>
        <execute template="rootentity" filename="ExtensiongroupRoot.java" useentityinfo="ExtensiongroupRoot"/>
        <execute template="entity" filename="Cd.java" useentityinfo="Cd"/>
        <execute template="entity" filename="Folder.java" useentityinfo="Folder"/>
        <execute template="entity" filename="File.java" useentityinfo="File"/>
        <execute template="entity" filename="Extensiongroup.java" useentityinfo="Extensiongroup"/>
        <execute template="entity" filename="Extension.java" useentityinfo="Extension"/>
    </folder>
    <folder project="CD Archive - generated" location="java" package="uk.org.rlinsdale.cdarchive.nodes" message="generating node files" log="linsdale.cdarchive" license="gpl30" datapackage="uk.org.rlinsdale.cdarchive.dataobjects">
        <execute template="rootnode" type="" filename="CdRootNode.java" useentityinfo="CdRoot"/>
        <execute template="rootnode" type="" filename="FileRootNode.java" useentityinfo="FileRoot"/>
        <execute template="rootnode" type="" filename="FolderRootNode.java" useentityinfo="FolderRoot"/>
        <execute template="rootnode" type="" filename="ExtensiongroupRootNode.java" useentityinfo="ExtensiongroupRoot"/>
        <execute template="node" type="" filename="CdNode.java" useentityinfo="Cd"/>
        <execute template="node" type="" filename="FileNode.java" useentityinfo="File"/>
        <execute template="node" type="" filename="FolderNode.java" useentityinfo="Folder"/>
        <execute template="node" type="" filename="ExtensiongroupNode.java" useentityinfo="Extensiongroup"/>
        <execute template="node" type="" filename="ExtensionNode.java" useentityinfo="Extension"/>
        <execute template="nodefactory" type="" filename="CdRootNodeChildFactory.java" useentityinfo="CdRoot"/>
        <execute template="nodefactory" type="" filename="FileRootNodeChildFactory.java" useentityinfo="FileRoot"/>
        <execute template="nodefactory" type="" filename="FolderRootNodeChildFactory.java" useentityinfo="FolderRoot"/>
        <execute template="nodefactory" type="" filename="ExtensiongroupRootNodeChildFactory.java" useentityinfo="ExtensiongroupRoot"/>
        <execute template="nodefactory" type="" filename="ExtensiongroupNodeChildFactory.java" useentityinfo="Extensiongroup"/>
        <execute template="undonode" filename="UndoExtensiongroupNode.java" useentityinfo="Extensiongroup"/>
        <execute template="undonode" filename="UndoExtensionNode.java" useentityinfo="Extension"/>
        <execute template="addnode" filename="AddExtensiongroupNode.java" useentityinfo="Extensiongroup"/>
        <execute template="addnode" filename="AddExtensionNode.java" useentityinfo="Extension"/>
    </folder>
    <folder project="CD Archive - generated" location="java" package="uk.org.rlinsdale.cdarchive.topcomponents" message="generating node viewer files" log="linsdale.cdarchive" license="gpl30" datapackage="uk.org.rlinsdale.cdarchive.dataobjects" nodepackage="uk.org.rlinsdale.cdarchive.nodes">
        <execute template="rootnodeviewer" type="Tree" filename="CdRootNodeViewer.java" useentityinfo="CdRoot"/>
        <execute template="rootnodeviewer" type="Tree" filename="ExtensiongroupRootNodeViewer.java" useentityinfo="ExtensiongroupRoot"/>
    </folder>
</nbpcg-build>

=== Richard-Linsdale/nbpcg/src/main/generated-xml/authentication-build.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE nbpcg-build PUBLIC "-//uk/org/rlinsdale/nbpcgbuild/DTD NBPCGBUILD SCHEMA 1.0//EN" "nbres:/uk/org/rlinsdale/nbpcg/nbpcgbuild.dtd">
<nbpcg-build name="Authentication">
    <folder name="data" project="LindosLifeCycleLibrary" package="uk.org.rlinsdale.lindos.authentication.dataobjects"/>
    <scriptfolder project="LindosLifeCycleLibrary"/>
    <execute action="message" message="generating script files"/>
    <execute action="entitytemplate" template="create" folder="script" filename="authentication-createdb.sql" usedbinfo="authentication" log="uk.org.rlinsdale.lindos.lifecycle" package="generated-scripts" license="gpl30"/>
    <execute action="entitytemplate" template="backupscript" folder="script" filename="authentication-backupscript.sh" usedbinfo="authentication" log="uk.org.rlinsdale.lindos.lifecycle" package="generated-scripts" license="gpl30"/>
    <execute action="entitytemplate" template="createtables" folder="script" filename="authentication-createtables.sql" usedbinfo="authentication" log="uk.org.rlinsdale.lindos.lifecycle" package="generated-scripts" license="gpl30"/>
    <execute action="message" message="generating data files"/>
    <execute action="entitytemplate" template="rootentity" folder="data" filename="UserRoot.java" useentityinfo="UserRoot" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
    <execute action="entitytemplate" template="rootentity" folder="data" filename="ApplicationRoot.java" useentityinfo="ApplicationRoot" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
    <execute action="entitytemplate" template="entity" folder="data" filename="User.java" useentityinfo="User" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
    <execute action="entitytemplate" template="entity" folder="data" filename="Application.java" useentityinfo="Application" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
    <execute action="entitytemplate" template="entity" folder="data" filename="Role.java" useentityinfo="Role" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
    <execute action="entitytemplate" template="entity" folder="data" filename="Permission.java" useentityinfo="Permission" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
    <execute action="entitytemplate" template="entity" folder="data" filename="Userrole.java" useentityinfo="Userrole" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
    <execute action="entitytemplate" template="entity" folder="data" filename="Userpermission.java" useentityinfo="Userpermission" nodepackage="" log="uk.org.rlinsdale.lindos.lifecycle" package="uk.org.rlinsdale.lindos.authentication.dataobjects" license="gpl30"/>
</nbpcg-build>

=== Richard-Linsdale/nbpcg/src/main/generated-xml/photogallery-build.xml
<?xml version="1.0" encoding="UTF-8"?>
    
    <!DOCTYPE nbpcg-build PUBLIC "-//uk/theretiredprogrammer/nbpcgbuild/DTD NBPCGBUILD SCHEMA 1.0//EN" "nbres:/uk/theretiredprogrammer/nbpcg/nbpcgbuild.dtd">
<nbpcg-build name="Photogallery" copyright="2015 Richard Linsdale (richard at theretiredprogrammer.uk)">
    <folder project="Photo Gallery - generated" location="resource" package="uk.theretiredprogrammer.photogallery.mysql" message="generating mysql script files for photogallery2" log="linsdale.photogallery" license="gpl30">
        <execute template="createsqldatabase" filename="createdb.sql" usepersistencestore="photogallery"/>
        <execute template="createsqldatabase" filename="createdb.sql" usepersistencestore="authentication"/>
        <execute template="backupscript" filename="backupscript.sh" usepersistencestore="photogallery"/>
        <execute template="backupscript" filename="backupscript.sh" usepersistencestore="authentication"/>
        <execute template="createsqltables" filename="createtables.sql" usepersistencestore="photogallery"/>
        <execute template="createsqltables" filename="createtables.sql" usepersistencestore="authentication"/>
    </folder>
    <folder project="Photo Gallery - generated" location="resource" package="uk.theretiredprogrammer.photogallery.mysql" message="generating mysql script files for authentication2" log="linsdale.photogallery" license="gpl30">
        <execute template="createsqldatabase" filename="createdb.sql" usepersistencestore="photogallery"/>
        <execute template="createsqldatabase" filename="createdb.sql" usepersistencestore="authentication"/>
        <execute template="backupscript" filename="backupscript.sh" usepersistencestore="photogallery"/>
        <execute template="backupscript" filename="backupscript.sh" usepersistencestore="authentication"/>
        <execute template="createsqltables" filename="createtables.sql" usepersistencestore="photogallery"/>
        <execute template="createsqltables" filename="createtables.sql" usepersistencestore="authentication"/>
    </folder>
    <folder project="Photo Gallery - generated" location="java" package="uk.theretiredprogrammer.photogallery.dataobjects" message="generating entity files" log="linsdale.photogallery" license="gpl30">
        <execute template="rootentity" filename="AlbumRoot.java" useentityinfo="AlbumRoot"/>
        <execute template="entity" filename="Album.java" useentityinfo="Album"/>
        <execute template="entity" filename="Albumpermission.java" useentityinfo="Albumpermission"/>
        <execute template="entity" filename="Group.java" useentityinfo="Group"/>
        <execute template="entity" filename="Albumgrouppermission.java" useentityinfo="Albumgrouppermission"/>
        <execute template="entity" filename="Image.java" useentityinfo="Image"/>
        <execute template="entity" filename="User.java" useentityinfo="User"/>
    </folder>
    <folder project="Photo Gallery - generated" location="java" package="uk.theretiredprogrammer.photogallery.nodes" message="generating node files" log="linsdale.photogallery" license="gpl30" datapackage="uk.theretiredprogrammer.photogallery.dataobjects">
        <execute template="rootnode" type="" filename="AlbumRootNode.java" useentityinfo="AlbumRoot"/>
        <execute template="rootnode" type="Icon" filename="AlbumRootIconNode.java" useentityinfo="AlbumRoot"/>
        <execute template="node" type="" filename="AlbumNode.java" useentityinfo="Album"/>
        <execute template="node" type="Icon" filename="AlbumIconNode.java" useentityinfo="Album"/>
        <execute template="node" type="" filename="ImageNode.java" useentityinfo="Image"/>
        <execute template="node" type="Icon" filename="ImageIconNode.java" useentityinfo="Image"/>
        <execute template="node" type="" filename="AlbumpermissionNode.java" useentityinfo="Albumpermission"/>
        <execute template="node" type="" filename="UserNode.java" useentityinfo="User"/>
        <execute template="node" type="" filename="AlbumgrouppermissionNode.java" useentityinfo="Albumgrouppermission"/>
        <execute template="node" type="" filename="GroupNode.java" useentityinfo="Group"/>
        <execute template="nodefactory" type="" filename="AlbumRootNodeChildFactory.java" useentityinfo="AlbumRoot"/>
        <execute template="nodefactory" type="" filename="AlbumNodeChildFactory.java" useentityinfo="Album"/>
        <execute template="nodefactory" type="Icon" filename="AlbumRootIconNodeChildFactory.java" useentityinfo="AlbumRoot"/>
        <execute template="nodefactory" type="Icon" filename="AlbumIconNodeChildFactory.java" useentityinfo="Album"/>
        <execute template="nodefactory" type="" filename="AlbumpermissionNodeChildFactory.java" useentityinfo="Albumpermission"/>
        <execute template="nodefactory" type="" filename="AlbumgrouppermissionNodeChildFactory.java" useentityinfo="Albumgrouppermission"/>
        <execute template="undonode" filename="UndoAlbumNode.java" useentityinfo="Album"/>
        <execute template="undonode" filename="UndoImageNode.java" useentityinfo="Image"/>
        <execute template="undonode" filename="UndoAlbumpermissionNode.java" useentityinfo="Albumpermission"/>
        <execute template="undonode" filename="UndoUserNode.java" useentityinfo="User"/>
        <execute template="undonode" filename="UndoAlbumgrouppermissionNode.java" useentityinfo="Albumgrouppermission"/>
        <execute template="undonode" filename="UndoGroupNode.java" useentityinfo="Group"/>
        <execute template="addnode" filename="AddAlbumNode.java" useentityinfo="Album"/>
        <execute template="addnode" filename="AddImageNode.java" useentityinfo="Image"/>
        <execute template="addnode" filename="AddAlbumpermissionNode.java" useentityinfo="Albumpermission"/>
        <execute template="addnode" filename="AddUserNode.java" useentityinfo="User"/>
        <execute template="addnode" filename="AddAlbumgrouppermissionNode.java" useentityinfo="Albumgrouppermission"/>
        <execute template="addnode" filename="AddGroupNode.java" useentityinfo="Group"/>
    </folder>
    <folder project="Photo Gallery - generated" location="java" package="uk.theretiredprogrammer.photogallery.topcomponents" message="generating node viewer files" log="linsdale.photogallery" license="gpl30" datapackage="uk.theretiredprogrammer.photogallery.dataobjects" nodepackage="uk.theretiredprogrammer.photogallery.nodes">
        <execute template="rootnodeviewer" type="Tree" filename="AlbumRootNodeViewer.java" useentityinfo="AlbumRoot"/>
        <execute template="rootnodeviewer" type="Icon" filename="AlbumRootIconNodeViewer.java" useentityinfo="AlbumRoot"/>
        <execute template="iconnodeviewer" filename="ImageIconNodeViewer.java" useentityinfo="Image"/>
    </folder>
    <folder project="Photo Gallery - generated" location="java" package="uk.theretiredprogrammer.photogallery.topcomponents" message="generating node editor files" log="linsdale.photogallery" license="gpl30" datapackage="uk.theretiredprogrammer.photogallery.dataobjects" nodepackage="uk.theretiredprogrammer.photogallery.nodes">
        <execute template="nodeeditor" filename="AlbumNodeEditor.java" useentityinfo="Album"/>
        <execute template="nodeeditor" filename="AlbumpermissionNodeEditor.java" useentityinfo="Albumpermission"/>
        <execute template="nodeeditor" filename="GroupNodeEditor.java" useentityinfo="Group"/>
        <execute template="nodeeditor" filename="AlbumgrouppermissionNodeEditor.java" useentityinfo="Albumgrouppermission"/>
        <execute template="nodeeditor" filename="ImageNodeEditor.java" useentityinfo="Image"/>
        <execute template="nodeeditor" filename="UserNodeEditor.java" useentityinfo="User"/>
        <execute template="editnode" filename="EditAlbumNode.java" useentityinfo="Album"/>
        <execute template="editnode" filename="EditImageNode.java" useentityinfo="Image"/>
        <execute template="editnode" filename="EditAlbumpermissionNode.java" useentityinfo="Albumpermission"/>
        <execute template="editnode" filename="EditUserNode.java" useentityinfo="User"/>
        <execute template="editnode" filename="EditAlbumgrouppermissionNode.java" useentityinfo="Albumgrouppermission"/>
        <execute template="editnode" filename="EditGroupNode.java" useentityinfo="Group"/>
        <execute template="choice" filename="ImageChoiceField.java" useentityinfo="Image"/>
        <execute template="enumchoice" filename="AlbumpermissionPermissionChoiceField.java" useentityinfo="Albumpermission" usefield="permission"/>
        <execute template="enumchoice" filename="AlbumgrouppermissionPermissionChoiceField.java" useentityinfo="Albumgrouppermission" usefield="permission"/>
    </folder>
</nbpcg-build>
