=== Richard-Linsdale/nbpcg/src/main/resources/uk/org/rlinsdale/nbpcg/nbpcgentityinfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    SYSTEM ID  : nbres:/uk/org/rlinsdale/nbpcg/nbpcgentityinfo.dtd

    Author     : Richard Linsdale (richard.linsdale at blueyonder.co.uk)
-->

<!ELEMENT nbpcg-entity-info (entityinfo+, persistencestore+) >
    <!ATTLIST nbpcg-entity-info
        name CDATA #REQUIRED
        >
    <!ELEMENT entityinfo (field*, child*, referenced*, sortformat*, displaytitleformat*, displaynameformat*)  >
        <!ATTLIST entityinfo
            name CDATA #REQUIRED
            pkey CDATA #IMPLIED
            pkeytype (Integer|String|Boolean) #IMPLIED
            pkeytypefunction CDATA #IMPLIED
            isroot CDATA #IMPLIED
            nodeorder CDATA #IMPLIED
            nomodifiers (yes) #IMPLIED
            customchildfactorypackage CDATA #IMPLIED
            dynamicicon CDATA #IMPLIED
            childnodesineditor CDATA #IMPLIED
            dbkey CDATA #IMPLIED
            dbtablename CDATA #IMPLIED 
            parentname CDATA #IMPLIED
            ordercolumn CDATA #IMPLIED
            orderable (yes|no) #IMPLIED
            label CDATA #IMPLIED
            viewers CDATA #IMPLIED
            icon CDATA #REQUIRED 
            >
        <!ELEMENT field EMPTY  >
            <!ATTLIST field
                name CDATA #REQUIRED
                pkey CDATA #REQUIRED
                fkey (no) #IMPLIED
                hidden (yes) #IMPLIED
                final (yes) #IMPLIED
                type (rootref|ref|String|int|reference|date|enum|idx|datetime|boolean|long|password) #REQUIRED
                references CDATA #IMPLIED
                label CDATA #REQUIRED
                values CDATA #IMPLIED
                javatype (int|String|DateOnly|Timestamp|boolean|long) #REQUIRED
                jsontype (Integer|String|Boolean|Long) #REQUIRED
                initialisation CDATA #REQUIRED
                choicemethod CDATA #IMPLIED
                unique (yes) #IMPLIED
                optional (yes) #IMPLIED
                index (unique|yes) #IMPLIED
                min CDATA #IMPLIED
                max CDATA #IMPLIED
                fieldclass (TextField|ReferenceChoiceField|EnumChoiceField|PasswordField|CheckboxField) #IMPLIED
                entryfield CDATA #IMPLIED
                passwordsupport CDATA #IMPLIED
                passwordstrength (none|weak|strong|verystrong) #IMPLIED
                >
        <!ELEMENT child EMPTY  >
            <!ATTLIST child
                name CDATA #REQUIRED
                dbname CDATA #IMPLIED 
                references CDATA #REQUIRED
                sort (yes|no) #REQUIRED
                orderable (yes|no) #REQUIRED
                copymoveentity CDATA #IMPLIED 
                copymovefield CDATA #IMPLIED
                hasiconview (yes|no) #REQUIRED
                isiconchild CDATA #IMPLIED
                >
        <!ELEMENT referenced EMPTY  >
            <!ATTLIST referenced
                name CDATA #REQUIRED
                field CDATA #REQUIRED
                optional CDATA #IMPLIED
                >
        <!ELEMENT sortformat (display*)  >
            <!ATTLIST sortformat
                format CDATA #REQUIRED
                >
        <!ELEMENT displaynameformat  (display*)  >
            <!ATTLIST displaynameformat
                format CDATA #REQUIRED
                >
        <!ELEMENT displaytitleformat  (display*)  >
            <!ATTLIST displaytitleformat
                format CDATA #REQUIRED
                >
            <!ELEMENT display EMPTY >
                <!ATTLIST display 
                    field CDATA #REQUIRED
                    length CDATA #IMPLIED
                    >
    <!ELEMENT persistencestore (persistenceentity+) >
        <!ATTLIST persistencestore
            name CDATA #REQUIRED
            dbname CDATA #REQUIRED
            >
        <!ELEMENT persistenceentity (persistencefield*, insertentity*) >
            <!ATTLIST persistenceentity
                name CDATA #REQUIRED
                >
            <!ELEMENT persistencefield EMPTY>
                    <!ATTLIST persistencefield
                        name CDATA #REQUIRED
                        final (yes) #IMPLIED
                        sys (yes) #IMPLIED
                        jsontype (String|Integer|Reference|Boolean) #REQUIRED
                        primarykey CDATA #REQUIRED
                        createsql CDATA #REQUIRED
                        min CDATA #IMPLIED
                        max CDATA #IMPLIED
                        nullallowed CDATA #IMPLIED
                        >
            <!ELEMENT insertentity (insertfield*, insertautopkfield*, insertorderablefield*)>
                <!ELEMENT insertfield EMPTY>
                    <!ATTLIST insertfield
                        name CDATA #REQUIRED
                        quote CDATA #IMPLIED
                        value CDATA #IMPLIED
                        var CDATA #IMPLIED
                        >
                <!ELEMENT insertautopkfield EMPTY>
                    <!ATTLIST insertautopkfield
                        name CDATA #REQUIRED
                        >
                <!ELEMENT insertorderablefield EMPTY>
                    <!ATTLIST insertorderablefield
                        name CDATA #REQUIRED
                        >

=== Richard-Linsdale/nbpcg/src/main/resources/uk/theretiredprogrammer/nbpcg/impl/accesscontrolmanager-entityinfo.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE nbpcg-entity-info PUBLIC "-//uk/theretiredprogrammer/nbpcgentityinfo/DTD NBPCGENTITYINFO SCHEMA 1.0//EN" "nbres:/uk/theretiredprogrammer/nbpcg/nbpcgentityinfo.dtd">
<nbpcg-entity-info name="Access Control Manager">
    <entityinfo name="User" dbkey="auth" dbtablename="User" pkey="id" pkeytype="Integer" pkeytypefunction="getInt" icon="user" orderable="no" nodeorder="1" parentname="UserRoot">
        <field name="root" pkey="no" references="UserRoot" type="rootref" label="Root" javatype="int" jsontype="Integer" initialisation=""/>
        <field name="username" pkey="no" unique="yes" min="1" max="100" fieldclass="TextField" type="String" label="Username" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="encodedpassword" pkey="no" min="40" max="40" fieldclass="TextField" type="String" label="Encodedpassword" javatype="String" jsontype="String" initialisation=" = &quot;&quot;" useentryfield="password"/>
        <field name="moniker" pkey="no" unique="yes" min="1" max="4" fieldclass="TextField" type="String" label="Moniker" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="enabled" pkey="no" fieldclass="CheckboxField" type="boolean" label="Enabled" javatype="boolean" jsontype="Boolean" initialisation=" = false"/>
        <field name="id" pkey="yes" hidden="yes" type="int" fieldclass="IntegerField" label="Id" javatype="int" jsontype="Integer" initialisation=" = 0"/>
        <field name="createdby" pkey="no" hidden="yes" type="String" min="4" max="4" fieldclass="TextField" label="Created by" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="createdon" pkey="no" final="yes" hidden="yes" type="datetime" fieldclass="DatetimeField" label="Created on" javatype="Timestamp" jsontype="String" initialisation=" = new Timestamp()"/>
        <field name="updatedby" pkey="no" hidden="yes" type="String" min="4" max="4" fieldclass="TextField" label="Updated by" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="updatedon" pkey="no" final="yes" hidden="yes" type="datetime" fieldclass="DatetimeField" label="Updated on" javatype="Timestamp" jsontype="String" initialisation=" = new Timestamp()"/>
        <entryfield name="password" type="password" label="Password" mapsto="encodedpassword" mapping="uk.theretiredprogrammer.accesscontrolmanager.helpers.AuthHelper.encodePassword" rule="uk.theretiredprogrammer.accesscontrolmanager.helpers.AuthHelper.strongPasswordCheck" errormessage="Strong Password required"/>
        <child name="claim" hasiconview="no" dbname="user" references="Claim" orderable="no" sort="no"/>
        <displaynameformat format="{0}">
            <display field="Username"/>
        </displaynameformat>
    </entityinfo>
    <entityinfo name="Claim" dbkey="auth" dbtablename="Claim" pkey="id" pkeytype="Integer" pkeytypefunction="getInt" icon="key" orderable="no" parentname="User" nodeorder="1">
        <field name="claimkey" pkey="no" min="1" max="100" fieldclass="TextField" type="String" label="Claimkey" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="value" pkey="no" min="1" max="200" fieldclass="TextField" type="String" label="Value" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="user" pkey="no" references="User" fieldclass="EntityChoiceField" type="ref" label="User" javatype="int" jsontype="Integer" initialisation=""/>
        <field name="id" pkey="yes" hidden="yes" type="int" fieldclass="IntegerField" label="Id" javatype="int" jsontype="Integer" initialisation=" = 0"/>
        <field name="createdby" pkey="no" hidden="yes" type="String" min="4" max="4" fieldclass="TextField" label="Created by" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="createdon" pkey="no" final="yes" hidden="yes" type="datetime" fieldclass="DatetimeField" label="Created on" javatype="Timestamp" jsontype="String" initialisation=" = new Timestamp()"/>
        <field name="updatedby" pkey="no" hidden="yes" type="String" min="4" max="4" fieldclass="TextField" label="Updated by" javatype="String" jsontype="String" initialisation=" = &quot;&quot;"/>
        <field name="updatedon" pkey="no" final="yes" hidden="yes" type="datetime" fieldclass="DatetimeField" label="Updated on" javatype="Timestamp" jsontype="String" initialisation=" = new Timestamp()"/>
        <displaynameformat format="{0}">
            <display field="Claimkey"/>
        </displaynameformat>
    </entityinfo>
    <entityinfo name="UserRoot" isroot="" label="Users" viewers="Manager" icon="folder_user">
        <child name="user" references="User" hasiconview="no" orderable="no" sort="no"/>
    </entityinfo>
    <persistencestore name="auth" dbname="auth" location="http:localhost:8080/auth/entity">
        <persistenceentity name="User">
            <persistencefield name="username" primarykey="no" jsontype="String" min="1" max="100" createsql=" VARCHAR(100) UNIQUE NOT NULL"/>
            <persistencefield name="encodedpassword" primarykey="no" jsontype="String" min="40" max="40" createsql=" CHAR(40)  NOT NULL"/>
            <persistencefield name="moniker" primarykey="no" jsontype="String" min="1" max="4" createsql=" VARCHAR(4) UNIQUE NOT NULL"/>
            <persistencefield name="enabled" primarykey="no" jsontype="Boolean" createsql=" BOOLEAN  NOT NULL"/>
            <persistencefield name="id" sys="yes" jsontype="Integer" primarykey="auto" createsql="MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY"/>
            <persistencefield name="createdby" sys="yes" primarykey="no" jsontype="String" min="4" max="4" createsql="CHAR(4) NOT NULL"/>
            <persistencefield name="createdon" final="yes" sys="yes" primarykey="no" jsontype="String" min="14" max="14" createsql="CHAR(14) NOT NULL"/>
            <persistencefield name="updatedby" sys="yes" primarykey="no" jsontype="String" min="4" max="4" createsql="CHAR(4) NOT NULL"/>
            <persistencefield name="updatedon" final="yes" sys="yes" primarykey="no" jsontype="String" min="14" max="14" createsql="CHAR(14) NOT NULL"/>
            <insertentity>
                <insertfield name="username" quote="yes" value="richard@rlinsdale.uk"/>
                <insertfield name="encodedpassword" quote="yes" value="ea27671eaac43ca1ecb782b7c9e9344a82b0702d"/>
                <insertfield name="moniker" quote="yes" value="rl"/>
                <insertfield name="enabled" quote="no" value="true"/>
                <insertfield name="createdby" quote="yes" var="USERCODE"/>
                <insertfield name="createdon" quote="yes" var="NOW"/>
                <insertfield name="updatedby" quote="yes" var="USERCODE"/>
                <insertfield name="updatedon" quote="yes" var="NOW"/>
                <insertautopkfield name="id"/>
            </insertentity>
        </persistenceentity>
        <persistenceentity name="Claim">
            <persistencefield name="claimkey" primarykey="no" jsontype="String" min="1" max="100" createsql=" VARCHAR(100)  NOT NULL"/>
            <persistencefield name="value" primarykey="no" jsontype="String" min="1" max="200" createsql=" VARCHAR(200)  NOT NULL"/>
            <persistencefield name="user" primarykey="no" jsontype="Reference" createsql="MEDIUMINT UNSIGNED NOT NULL ,FOREIGN KEY (user) REFERENCES User(id)"/>
            <persistencefield name="id" sys="yes" jsontype="Integer" primarykey="auto" createsql="MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY"/>
            <persistencefield name="createdby" sys="yes" primarykey="no" jsontype="String" min="4" max="4" createsql="CHAR(4) NOT NULL"/>
            <persistencefield name="createdon" final="yes" sys="yes" primarykey="no" jsontype="String" min="14" max="14" createsql="CHAR(14) NOT NULL"/>
            <persistencefield name="updatedby" sys="yes" primarykey="no" jsontype="String" min="4" max="4" createsql="CHAR(4) NOT NULL"/>
            <persistencefield name="updatedon" final="yes" sys="yes" primarykey="no" jsontype="String" min="14" max="14" createsql="CHAR(14) NOT NULL"/>
            <insertentity>
                <insertfield name="claimkey" quote="yes" value="trp.acm.ok"/>
                <insertfield name="value" quote="yes" value="yes"/>
                <insertfield name="user" quote="no" value="1"/>
                <insertfield name="createdby" quote="yes" var="USERCODE"/>
                <insertfield name="createdon" quote="yes" var="NOW"/>
                <insertfield name="updatedby" quote="yes" var="USERCODE"/>
                <insertfield name="updatedon" quote="yes" var="NOW"/>
                <insertautopkfield name="id"/>
            </insertentity>
        </persistenceentity>
    </persistencestore>
</nbpcg-entity-info>
